default_stages: [commit, push]
default_language_version:
  python: python3.9
exclude: ".git|.tox|.idea"
fail_fast: true
repos:
  ### general ###
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10240"] # 10MB
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: file-contents-sorter
      - id: mixed-line-ending
      - id: sort-simple-yaml
      - id: trailing-whitespace
